name: Build and Deploy Android to Firebase

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.4'  # Substitua pela versão do Flutter desejada

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android app
        run: flutter build apk --release

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TASKPLANAPP }}'
          channelId: live
          projectId: taskplanapp# Substitua pela variável de ambiente contendo o token do Firebase

