name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      flutter-version:
        description: 'Versão do Flutter'
        required: true
        default: '3.16.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Cache Dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.pub-cache
        key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pub-

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ github.event.inputs.flutter-version }}

    - name: Install Dependencies
      run: flutter pub get
      
    - name: Build APK
      run: flutter build apk

    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build/

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        name: build
        path: build/

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Set Version
      id: set_version
      run: echo "::set-output name=version::$(git rev-list --count HEAD)"

    - name: Check Existing Tag
      run: |
        cd $GITHUB_WORKSPACE
        if [[ -z "$(git tag -l 'v${{ steps.set_version.outputs.version }}')" ]]; then
          git tag -a "v${{ steps.set_version.outputs.version }}" -m "Release version v${{ steps.set_version.outputs.version }}"
          git push origin "v${{ steps.set_version.outputs.version }}"
        else
          echo "Tag v${{ steps.set_version.outputs.version }} already exists."
        fi

    - name: Deploy to Release Page
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/app/outputs/flutter-apk/app-release.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
